# Generated by Django 5.0.1 on 2024-01-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ban',
            new_name='Band',
        ),
    ]
